#! /bin/sh

killall polybar &
kilall picom &

bspc monitor -d  1 2 3 4 5 6 7 8 9 10

bspc config border_width                 2
bspc config window_gap                   8

bspc config split_ratio                  0.5
bspc config borderless_monocle           true
bspc config gapless_monocle              true
bspc config focus_follows_pointer        true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# set a wallpaper
feh --bg-scale ~/Pictures/forest.jpg &

# launch polybar(s)
# ~/.config/polybar/launch.sh
polybar top-left &
polybar bottom-right &
polybar bottom-left &

# start notification manager
dunst &

# start picom
# picom &
picom --experimental-backends -b &
